sonar.projectKey=oclkadev_sumup
sonar.organization=oclka-1

sonar.sources=src

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.cpd.exclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.coverage.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,src/**/__e2e__/**,src/**/__tests__/**,src/**/types/**,src/commands/index.ts,src/commands/options.ts,src/commands/test/index.ts,src/core/errors/app-error.ts,src/core/errors/codes.ts,src/core/errors/index.ts,src/core/helpers/index.ts,src/index.ts

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.javascript.node.maxspace=4096
