name: Size Limit

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    name: 📏 Bundle Size
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HUSKY: 0

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 🏗️ Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: 📦 Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: 🏗️ Build
        run: pnpm build

      - name: 📏 Report Bundle Size
        uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_step: build
